language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - hhvm

before_script:
  - composer install --no-interaction --prefer-source --dev

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  email:
    - anthony.k.gross@gmail.com
